### PR TITLE
meanBy -- arithmetic mean value

### PR DESCRIPTION
**Pull request by lolmaus**
With test and Readme entry!

### CODE REVIEW

**Comment by lolmaus** [comment]
This will also give you your 8th mark on EmberObserver. :D

**Comment by martndemus** [comment]
Thanks! More pull requests for other statistics methods are welcome!

**Comment by lolmaus** [comment]
If I encounter a need in another macro, I'll file another PR.

Any ETA on merging and releasing this one?

**Comment by martndemus** [comment]
As soon as I fixed circle, I'll merge and release

**Comment by martndemus** [comment]
@lolmaus Version 1.3.0 published

**Comment by lolmaus** [comment]
Awesome, thank you!

**Comment by lolmaus** [comment]
Congrats with 8/10 on EmberObserver! :D

**Comment by martndemus** [comment]
Thanks!

**Pull request merged**
