### PR TITLE
Fixed #5: meanBy returns NAN when listProperty is a relationship

### LINKED ISSUE #5: meanBy returns NAN when listProperty is a relationship
The cause of the problem is that a relationship is not a real array, it's an object with an array-like API. `list.length` is a computed property and does not return a value when accessed like that. It must be accessed via a getter.

### PR DESCRIPTION
**Pull request by lolmaus**
Includes #7 (tests didn't work without it).

A failing test for #5 is in a separate commit: you can check it out to ensure the problem exists and is indeed fixed by the subsequent commit.

### CODE REVIEW

**Comment by martndemus** [comment]
Rebase please.

**Comment by lolmaus** [comment]
Can you please provide a command? I'm not good at rebasing.

PS Just realized that the bug I've fixed had been introduced by me. Crazy!

**Comment by martndemus** [comment]
`git reset --hard`
`git checkout master`
`git pull master`
`git checkout mean-by-relationships2`
`git rebase master`
`git push --force`

**Comment by lolmaus** [comment]
Done. What's the benefit, does it make git log cleaner? You're gonna have a merge commit either way, and this PR shouldn't have added more commits before rebasing than it will after?

**Comment by martndemus** [comment]
@lolmaus Yes it makes the git log cleaner.

**Comment by lolmaus** [comment]
Can you please explain the difference?

Here's the current log of `master`:

```
f2f0a2777658447f8da0fb48a10702f8c878b581 Merge pull request #9 from lolmaus/mean-by-relationships2
762e17a4674b8f7eb3d568eab9a7e24dc3f99162 Fixed #5: meanBy returns NAN when listProperty is a relationship
5c4d8a1d6306714ed7651cdab94275b10fa78632 Failing test for #5: meanBy returns NAN when listProperty is a relationship
763426159d0676c6cddfa7ebb231256788509100 Merge pull request #7 from lolmaus/ember-cli-upgrade
ed417ba26c284459764bc7e168d93358b0f9f971 Upgraded Ember CLI to 1.13.15, reenables tests, fixes #6
```

What would it look like if you merged the second PR without rebasing?

**Pull request merged**
